apiVersion: v1
kind: Namespace
metadata:
  name: webhook-cd

---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-environment-secret
  namespace: webhook-cd
type: Opaque
stringData:
  FINANCER_ACCESS_TOKEN_ROLLOUT_DEV: secret-token
  FINANCER_ACCESS_TOKEN_ROLLOUT_PROD: secret-token
  FINANCER_ACCESS_TOKEN_WEBHOOK: secret-token
